### ISSUE TITLE
General questions concerning Basket

### ISSUE THREAD

**Issue by nWidart** [philipbrown/basket#1]
Hello,

This package is looking to be **very** clean, I'm considering using this package for an e-commerce application. I'm reading your blog on 'Creating a PHP Shopping Basket' which is very nice.

I've got some questions though about the usage in general of the package.
1. Can products have additional meta data applied to them, and can some of those meta data needs to add an additional cost to the product?
2. From what I see, and what's pretty nice, is that this package is not dependent on a persistence layer. Could this package be used on an event-sourced application ? ([example app](https://github.com/qandidate-labs/broadway-demo/tree/master/src/BroadwayDemo/Basket))
3. For a more classical persistance approach, like Doctrine, how would you go about persisting the products, baskets and orders ?

Thank you,

**Comment by philipbrown** [comment]
Thank you Nicolas :smile:
1. No. That's actually a good point, there is no way of changing the meta data of a `Product` object. I'll have to have a think about that one.
2. Yes, actually an early version used events. I've been meaning to add those back in. So for example, events would be fired when a product was added, updated or removed from the basket.
3. I just stick the`Basket` in the session. The `Product` and `Order` should not be confused with the Domain Objects of your application. `PhilipBrown\Basket\Product` should not be used as your Domain Object as it is should only be scoped to sit within the basket service.

**Comment by nWidart** [comment]
Thank you for the clarification.
1. Would be nice to have that product meta data available.
2. Will wait for events to come back in then. 
3. Alright. So the real persisted product will be used to instantiate the `Basket\Product` class of this package.

Any reason why this package isn't on Packagist ? I couldn't find it using `philipbrown` as vendor name. I included it by adding the repo in the `repositories` key.

**Comment by philipbrown** [comment]
Cool, I'll look into adding those things soon.

Yeah I haven't got round to submitting it yet. I'll wait until I've finished the `1.0` version and then submit it then.

**Comment by philipbrown** [comment]
I'm going to close this issue and pick up these up in #3 and #4

**Comment by nWidart** [comment]
:+1: , Thanks. :smiley:

**Comment by dennisoderwald** [comment]
@nWidart Now you can use attributes :)

**Comment by nWidart** [comment]
Awesome! :+1:
