### ISSUE TITLE
Basket info before reconsiling

### ISSUE THREAD

**Issue by nWidart** [philipbrown/basket#11]
It would be nice to have basket information about totals, subtotals, coupons etc. before beginning the reconciling process.  

For instance for a current view of the basket, but before processing it to an order. Since there are already methods to get the taxrate and currency, more could be added ?

**Comment by philipbrown** [comment]
I think you are misunderstanding the reconciliation process. You don't necessarily have to only reconcile before saving to the database or to a payment gateway. You can reconcile on each page request so you have the calculated totals available as part of the view.

The `Basket` is the raw data, and the `Order` is the reconciled data. You would reconcile before displaying the data in the view.

This keeps the raw data and the reconciled data separate.

**Comment by nWidart** [comment]
Ah okay, I understand.

Though...

``` php
$reconciler = new DefaultReconciler;
$meta = [
    new DeliveryMetaData($reconciler),
    new DiscountMetaData($reconciler),
    new ProductsMetaData,
    new SubtotalMetaData($reconciler),
    new TaxableMetaData,
    new TaxMetaData($reconciler),
    new TotalMetaData($reconciler),
    new ValueMetaData($reconciler)
];
$processor = new Processor($reconciler, $meta);
```

I find that a lot of code to repeat, and even worse, to direct implementations, not abstractions (interfaces), this means I'm tightly coupled.

Don't get me wrong, it is very nice to have this data, but I think I'd prefer having this on the basket itself.

Also, why do I have to repeat myself:
- `$processor->meta($this->basket->current())`
- `$processor->products($this->basket->current())`

Instead of sending the basket to the processor directly:

``` php
// ...
$processor = new Processor($reconciler, $meta, $basket);
```
- `$processor->meta()`
- `$processor->products()`

**Comment by philipbrown** [comment]
Yeah, but I would hide that behind the implementation.

So you would have your project's interface:

``` php
interface MyShopBasket { }
```

Then you would create an implementation that uses this package and implements your interface:

``` php
class PhilipBrownBasket implements MyShopBasket { }
```

`PhilipBrownBasket` is just one implementation of your `MyShopBasket` interface.

Then you would have a method that returns the basket as a generic output to be displayed on the view or as a HTTP response. By returning the basket as a generic output, you aren't coupled to the objects of that single implementation.

The outside world does not know anything about the reconciliation process. A different implementation might not have that process as long as it returns the basket as an `array` or `json`

**Comment by nWidart** [comment]
Ah ok, I see.

Currently I [bound](https://github.com/nWidart/PhilipBrownBasket/blob/master/src/Ecommerce/BasketServiceProvider.php#L12-L14) my [`basket`](https://github.com/nWidart/PhilipBrownBasket/blob/master/src/Ecommerce/Application/Basket/Basket.php) interface directly with your implementation.
But I guess I'll bind that with a `PhilipBrownBasket` implementation like you suggest. But then that new basket interface would have all the current methods, plus the useful ones like one to get the meta data etc.

Though I still find the fact that I have to repeat myself when calling `->meta($basket)` and `->products($basket)`  on the processor. Instead of setting it once during instantiation and be done with it.
Also the fact that I can't just have a `$basket` variable, since the meta and the products are separated. That would mean I'd have to have a `$basketMeta` and `$basketProducts` variable in the view, which is less clear I think.

**Comment by philipbrown** [comment]
Once I've finished the `1.0` version I'll create an example implementation that will show how I think the package should be used. That should make things clearer.

**Comment by nWidart** [comment]
Okay thanks. Sorry for the trouble. :smiley: 

For now I've added a [`Basket`](https://github.com/nWidart/PhilipBrownBasket/blob/master/src/Ecommerce/Application/Basket/Basket.php) interface with its [implementation](https://github.com/nWidart/PhilipBrownBasket/blob/master/src/Ecommerce/Application/Basket/PhilipBrownBasket.php). 

Hope I'm on the right track with this. :)
