### ISSUE TITLE
Idea: Money Presenter

### ISSUE THREAD

**Issue by nWidart** [philipbrown/basket#12]
Hello,

Related to the [following issue](https://github.com/mathiasverraes/money/issues/91), would a Money presenter be a good idea ? Instead of returning `Money\Money` instance, returning a presenter from this package, as this would make the formatting easier.

The presenter could basically just have a `__toString` method

``` php
public function __toString()
{
    $formatter = new \NumberFormatter($jurisdiction->locale(), \NumberFormatter::CURRENCY);

    return $formatter->format($this->getAmount() / 100);
}
```

This would require the presence of a container though. Since we can't just instantiate `UnitedKingdom` or `Belgium` jurisdiction. But rather use the implementation bound to the `Jurisdiction` interface.

Thanks,

**Comment by nWidart** [comment]
I see you already have a [`MoneyFormatter`](https://github.com/philipbrown/basket/blob/065f40a47253f7ef86f37c0e1856f3a3ceb23194/src/Formatters/MoneyFormatter.php) which does this basically. Though this happens after the basket has been processed, if I'm not mistaken. Also, the formatters are used to process the order before persisting it, right ? But I'd like to persist the order prices using integers (cents) instead of floats.

**Comment by philipbrown** [comment]
No you would persist the order after it's been processed. The transformation stage is where the `Money` object is formatted for humans.
