### ISSUE TITLE
Allow custom Product data

### ISSUE THREAD

**Issue by philipbrown** [philipbrown/basket#4]
#1

**Comment by philipbrown** [comment]
I've decided to just leave this package as it is. Moving towards using interfaces and traits is a good idea, but it's getting away from the encapsulated design of this package.

I think implementing the same functionality as interfaces and traits would be more applicable as a separate package. I might have a look at doing this at some point, but I don't really have a need for it at the minute so I can't dedicate the time to it.

**Comment by dennisoderwald** [comment]
+1 - Is it okay if I add an attributes object with an array?
