### ISSUE TITLE
Idea: Adding basket interface

### ISSUE THREAD

**Issue by nWidart** [philipbrown/basket#7]
What do you think of renaming `Basket` to `DefaultBasket`, adding a basket interface which is implemented by the `DefaultBasket`. This would allow binding that in the laravel's IoC container.

**Comment by philipbrown** [comment]
Yeah I've been thinking about how open up the `Product` and `Basket` classes for extension. I think that's the right approach :smile:

I'm going to give it some more thought and then play around with some code. Ping me if you have any ideas or suggestions :smile:

**Comment by nWidart** [comment]
Okay, for now I've added a [basket interface](http://laravel.io/bin/aN502),  and bound that in the IoC container:

``` php
$this->app->bind('Modules\Ecommerce\Application\Basket\Basket', function () {
    return new Basket(new Belgium());
});
```

But issue with this now is that I can't inject the interface via a method argument, since your `Basket` class doesn't implement it. So for now I'm just using it like so: 

``` php
$this->basket = app('Modules\Ecommerce\Application\Basket\Basket');
```

Having an interface for the product might be nice too indeed.

**Comment by philipbrown** [comment]
I've decided to just leave this package as it is. Moving towards using interfaces and traits is a good idea, but it's getting away from the encapsulated design of this package.

I think implementing the same functionality as interfaces and traits would be more applicable as a separate package. I might have a look at doing this at some point, but I don't really have a need for it at the minute so I can't dedicate the time to it.
