### ISSUE TITLE
Adding same product to basket doesn't increment the product count

### ISSUE THREAD

**Issue by nWidart** [philipbrown/basket#9]
Steps:
- Adding a product to basket
- Adding that same product to basket again
- When looping over the products in the basket, `dd($product->quantity)` is still 1.

I'm aware it can be done like so:

``` php
if ($this->productIsInBasket($sku)) {
    $this->basket->update($sku, function(Product $product) {
        $product->increment();
    });
} else {
    $this->basket->add($sku, $request->get('name'), $price);
}
```

But wouldn't it be easier of the add method can do this already.

**Comment by philipbrown** [comment]
Yep already got this in #5

**Comment by nWidart** [comment]
Ah nice okay. Wasn't sure what that issue was about. :smiley:
